name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Submodules
      submodules: recursive
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Make
      env:
        PKGFORGE_STATEFILE: /tmp/pkgforge
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: make
    - name: Release
      env:
        PKGFORGE_STATEFILE: /tmp/pkgforge
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: startsWith(github.ref, 'refs/tags/')
      run: make release
    - name: Store
      uses: actions/upload-artifact@v3
      with:
        name: pkg
        path: pkg
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
